spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:5175"
            allowed-headers: "*"
            allowed-methods: "*"
            allow-credentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: secretValuesecretValuesecretValuesecretValuesecretValue
  expiration: 86400