GET http://localhost:8080/doctors/24
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJwcm9maWxlSWQiOiI4IiwiZW1haWwiOiJuZXdzdXJuYW1lQGdtYWlsLmNvbSIsImlkIjoiMSIsInJvbGUiOiJQQVRJRU5UIiwic3ViIjoiMSIsImlhdCI6MTcxNjgwNjcwMSwiZXhwIjoxNzE2ODkzMTAxfQ.-Y1qyo4zrLT252Ul5TWSTt9d3JfuUW95L_cx3wLPbZamQYyrBhmoy-9iUeQPcowH
